CV/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CV.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CV/Controllers/HomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CV.Controllers
{
    public class HomePageController : Controller
    {
        // GET: HomePage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Home()
        {
            return View();
        }

        public ActionResult Information()
        {
            return View();
        }
    }
}

CV/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CV/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CV/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CV/Views/HomePage/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="page-width-1 page-left">
    <div class="d-flex position-relative tm-border-top tm-border-bottom intro-container">
        <div class="intro-left tm-bg-dark">
            <h2 class="mb-4 text-center">Welcome to My Portfolio Website</h2>
            <p class="mb-4">
                This is the submission for Advanced Programming in .NET first assignment. There are four pages: Home, Personal Information, Educational Qualification and Skills and Experience.
            </p>
            <p class="mb-0">
                You are not permitted to redistribute this template on your Free CSS collection websites. Please <a rel="nofollow" href="https://templatemo.com/contact" target="_blank">contact us</a> for more information.
            </p>
        </div>

    </div>
</div>

CV/Views/HomePage/Information.cshtml
@{
    ViewBag.Title = "Information";
}

<h2 class="text-center">Personal Information</h2>

<section id="about" class="about">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <p>My name is Mohammed Jamshed Alam. I am currently a bachelor student in Computer Science & Engineering in American Internation University Bangladesh. My goal is to become a data scientist</p>
        </div>

        <div class="row">
            <div class="col-lg-8 pt-4 pt-lg-0 content">
                <div class="row">
                    <div class="col-lg-6">
                        <ul>
                            <li><i class="bi bi-rounded-right"></i> <strong>Birthday:</strong> 22 January 2000</li>
                            <li><i class="bi bi-rounded-right"></i> <strong>Linkedin:</strong> <a id="HyperLink1" href="https://www.linkedin.com/in/mohammed-jamshed-alam-6a2513222/">Mohammed Jamshed Alam</a></li>
                            <li><i class="bi bi-rounded-right"></i> <strong>Phone:</strong> 01794691454</li>
                            <li><i class="bi bi-rounded-right"></i> <strong>City:</strong> City : Dhaka, Bangladesh</li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul>
                            <li><i class="bi bi-rounded-right"></i> <strong>Age:</strong> 22</li>
                            <li><i class="bi bi-rounded-right"></i> <strong>Degree:</strong> Bachelors</li>
                            <li><i class="bi bi-rounded-right"></i> <strong>Email:</strong> alammohammedjamshed@gmail.com</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section><!-- End About Section -->

CV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Portfolio Website", "Home", "HomePage", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Home", "HomePage")</li>
                    <li>@Html.ActionLink("Personal Infromation", "Information", "HomePage")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer id="footer"><div class="container"><div class="copyright"> © Copyright <strong><span>Mohammed Jamshed Alam</span></strong>. All Rights Reserved</div></div></footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>